### ISSUE TITLE
Convert over to chillout please

### ISSUE THREAD

**Issue by brexmania123** [llealloo/vrc-udon-audio-link#187]
are there any plans to convert audio link to chillout vr. i hope so. thank you

**Comment by Pokeduel** [comment]
Supposedly i've heard minimal works if you want to try that

**Comment by pema99** [comment]
I've seen people use Audiolink in CVR before, but I don't know the steps involve. Google around for it, perhaps.

I don't think any active contributor is seriously considering something like this, but contributions are always welcome, in this case so long as they don't damage or impair the existing VRC use case.

**Comment by DomNomNomVR** [comment]
I'm looking into this at the moment.

**Comment by DomNomNomVR** [comment]
So it seems like the audio data from ChilloutVR makes it into the AudioLink shader via the CVRAudioMaterialParser component.

There is apparently a ported AudioLinkController prefab floating about in DM's but because of Rule §9 "Do not share assets of any kind." on the CVR discord, I have not yet been able to get my hands on it yet.

**Comment by DjShinter** [comment]
Audio link is already supported.

**Comment by DomNomNomVR** [comment]
@DjShinter Yes, but it seems like worlds still need to have something in them to drive the AudioLink render texture. That part still needs to have an official source.

**Comment by DomNomNomVR** [comment]
Someone got back to me about the package that exists already: https://domnomnom.com/ChilloutVR/CVR_AudioLink_Unofficial.unitypackage
Credit apparently goes to Khodrin.

In the long run I think it's better if there is a repo for this rather than a package shared in DM's or on a personal webserver.

**Comment by DomNomNomVR** [comment]
@llealloo What do you think is the best way to structure the repos? I'm putting my hand up to maintain the open source CVR side of things.

The approaches I can see:

 1. Maintain one repo and build both CVR and VRC releases from it
 1. Me creating a fork of this repo
 1. Create an agnostic shared repo for the core part which does not depend on a SDK of any game
 
My current opinion on these are:

 1. Centralized, which makes bug reports easy. Downside is that contributors need to have SDK's from both ChilloutVR and VRChat. The release process might need to get more complex to include / exclude the right things. Might confuse users who download the wrong build. Renaming the repo would be appropriate.
 1. Easy to make progress on in the short term. Might become annoying for maintainers in the long term if there's lots of features being added / changed which need merging across repos.
 1. I think this is the philosophically correct way of doing it but the worst in practice due to the potential for pain where there isn't a clean interface that's separable. For instance, the AudioLinkController itself has interwoven stuff that could be shared and parts that can't. There's the potential for version-hell where an interface change might be very easy to change on one side but hard on the other.

Overall, I prefer option 2.) at the moment but I want to hear other voices on this as I have lots of respect for the people who built this and I want cool shader stuff to happen no matter what platform people prefer.

**Comment by pema99** [comment]
FWIW I vote for the second version. Creating releases is currently quite manual, and development on AudioLink nowadays is generally pretty slow. It would also give you full control over the CVR related stuff, which I'm not sure how many of the regular contributors care too much about.

**Comment by llealloo** [comment]
I agree that as far as short term time tables go, option 2 seems like the best fit as well

As a heads up, it is likely in the coming months that there will be significant upgrades- including a new controller and addition of one or more new core features like auto-gain, etc.

Hopefully this helps inform your decision. While it is true that I currently don't have much personal interest or investment in official support for CVR, this doesn't mean that won't change in the future! Ultimately I am happy and excited to see people using taking advantage of the amazing teamwork & collaboration that's gone into AudioLink regardless of the platform.

**Comment by DomNomNomVR** [comment]
Sweet! :D
I've created a CVR fork over here: https://github.com/DomNomNomVR/cvr-audio-link
