### ISSUE TITLE
Audio Volume is set to 0.01 in Audiolink Script making the audio really quiet 

### ISSUE THREAD

**Issue by ARKAIKGD** [llealloo/vrc-udon-audio-link#3]
I've been trying to figure this out but since upgrading from 1.3 to 1.5 I noticed that everything I try has the same effect. The only way to get the audio-reactive elements to work makes the audio source set to 0.01 by the script, I have tried adding multiple audio sources to the Udon video player but the second audio source never works.

**Comment by llealloo** [comment]
As outlined in the readme, this is a known issue / current limitation due to the way the unity video player handles audio.

For now as a stop gap, AudioLink is only compatible with the AVPro based video players.

## Notes on currently available player prefabs
- USharpVideo player uses a hybrid approach, with the unity player for youtube and AVPro for streams. Only the streaming mode of this player is compatible.
- TechAnon's TV is also a hybrid, and is selectable between Unity vs AVPro. It is compatible in AVPro mode.
- NorixWolfe player is 100% AVPro, and is therefore fully compatible.

It is possible to make AudioLink work with the unity player, but not with 3D spatialized audio sources sure to the way that GetSpectrumData bases it's result on the Audio Listener (located at the player position / camera). Therefore with the unity player, the audio source must be 2D so that it does not attenuate the AudioLink result. For the time being, in order to reduce complexity of setup, and because of other performance issues inherent to the unity video player (it runs on the main thread for example), it is not supported.. in favor of the AVPro player.
